/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jp_keita_kagurazaka_jnisample_SomeNativeClassWrapper */

#ifndef _Included_jp_keita_kagurazaka_jnisample_SomeNativeClassWrapper
#define _Included_jp_keita_kagurazaka_jnisample_SomeNativeClassWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jp_keita_kagurazaka_jnisample_SomeNativeClassWrapper
 * Method:    nativeCreate
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_jp_keita_kagurazaka_jnisample_SomeNativeClassWrapper_nativeCreate
  (JNIEnv *, jclass);

/*
 * Class:     jp_keita_kagurazaka_jnisample_SomeNativeClassWrapper
 * Method:    nativeDestroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jp_keita_kagurazaka_jnisample_SomeNativeClassWrapper_nativeDestroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_keita_kagurazaka_jnisample_SomeNativeClassWrapper
 * Method:    nativeCalculate
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_jp_keita_kagurazaka_jnisample_SomeNativeClassWrapper_nativeCalculate
  (JNIEnv *, jclass, jlong);

/*
 * Class:     jp_keita_kagurazaka_jnisample_SomeNativeClassWrapper
 * Method:    nativeThrowException
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_jp_keita_kagurazaka_jnisample_SomeNativeClassWrapper_nativeThrowException
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
